name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 GMT
  workflow_dispatch:     # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap
        run: |
          npx sitemap-generator https://8hantanu.net \
            --output ./sitemap.xml \
            --strip-querystring \
            --max-depth 10 \
            --timeout 5000

      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml [cron]" || echo "No changes to commit"
          git push
